---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Roles for EC2 Instances"

Resources:
  # create an instance profile for accessing dynamodb and S3
  EC2DynamoAccess:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: EC2AccessRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: "AllowEC2PutItemsToDynamoDB"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "dynamodb:*"
                Resource: "*"

        - PolicyName: "AllowEC2ToS3PutAndGetItem"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "s3:*Object"
                Resource: "*"

  EC2AmiBuilderProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: EC2DynamoS3Access
      Roles:
        - !Ref EC2DynamoAccess
